### ISSUE TITLE
When do you plan to make a new version of the ZGuide?

### ISSUE THREAD

**Issue by metadings** [imatix/zguide#508]
When do you plan to make a new version of the ZGuide?

Should I rename all the sample files to lower-cased names, for the build-script?

https://github.com/metadings/zguide/tree/master/examples/C%23

**Comment by hintjens** [comment]
Yes, the filenames must match the originals, otherwise they don't get picked up by the processor. I'll make a new version later today then.

**Comment by metadings** [comment]
No no, don't hurry, I just want to know... Let's make some examples and then ;-)

**Comment by metadings** [comment]
Hello!

I've made the examples as noted in the [ToDo](https://github.com/metadings/zguide/issues/1) list!

Some examples are actually too hard to write them at once. As I wrote FLCliApi, I found that I'm going to do the basics, to get them ready until EAGAIN.

Do you want to let the processor run now, having most of the examples ready on zguide.zeromq.org?

**Comment by hintjens** [comment]
OK, I've updated the Guide online.

**Comment by metadings** [comment]
You're my man, Pieter!

**Comment by metadings** [comment]
This is just WOW :-)

I'm going to close this issue (for now)...
