### ISSUE TITLE
 Confused licensing on Java examples

### ISSUE THREAD

**Issue by braddockcg** [imatix/zguide#536]
I'm confused by the licensing of the java examples in zguide.  The guide text says they are MIT/X11.  The zguide/examples/Java/README says to see examples/LICENSE which says MIT/X11.  But a FEW of the Java source files say LGPL.  Can this be clarified? 

The follows Java example source files say LGPL.  Their wording actually seems to imply that all of ZGuide examples are LGPL, which adds to the confusion.

bstar.java
bstarsrv2.java
clonecli6.java
flclient2.java
mdbroker.java
mdcliapi2.java
mdcliapi.java
MDP.java
mdwrkapi.java

For my purposes it is confusing because a few of the majordomo pattern examples declare LGPL while other files of the same majordomo example do not specify so are presumably MIT.

Thanks,
Braddock

**Comment by hintjens** [comment]
I've fixed this and other cases of the same. At an early stage we had
licensed the example code under LGPL, and then switched to MIT/X11. These
examples were IMO not changed during that switch and/or inherited the old
LGPL header. In any case the license is MIT/X11 and so I've changed the
offending examples.

On Fri, Mar 20, 2015 at 12:28 AM, Braddock Gaskill <notifications@github.com

**Comment by braddockcg** [comment]
Great, thanks!
