### ISSUE TITLE
Chapter 2, "Recall that subscriptions do a prefix match." when it hasn't been mentioned yet.

### ISSUE THREAD

**Issue by abraithwaite** [imatix/zguide#549]
I was reading the guide and hit this unexpectedly.  It was the first time I've heard that subscriptions were done by prefix matching.  Thinking I had missed something, I quickly searched for anything containing prefix before that point.  It's the first instance of the word prefix on the version posted [here](http://zguide.zeromq.org/page:all).

I'm still reading through it, but I thought I would submit an issue before I forgot.

Absolutely fantastic writing though, very :bulb:.

**Comment by hintjens** [comment]
OK, fixed it in the sources. Thanks for catching this!
