### ISSUE TITLE
Will it be better to make lbbroker2.c/lbbroker3.c behave like lbbroker.c?

### ISSUE THREAD

**Issue by myd7349** [imatix/zguide#557]
[lbbroker.c](https://github.com/imatix/zguide/blob/master/examples/C/lbbroker.c)'s `client_task` is implemented like this:
```c
static void *
client_task(void *args)
{
    // ...
    //  Send request, get reply
    s_send(client, "HELLO");
    char *reply = s_recv(client);
    printf("Client: %s\n", reply);
    free(reply);
    zmq_close(client);
    zmq_ctx_destroy(context);
    return NULL;
}
```
and the program will exit after 10 messages.

[lbbroker2.c](https://raw.githubusercontent.com/imatix/zguide/master/examples/C/lbbroker2.c)'s `client_task` looks like this:
```c
static void *
client_task (void *args)
{
    // ...
    //  Send request, get reply
    while (true) {
        zstr_send (client, "HELLO");
        char *reply = zstr_recv (client);
        if (!reply)
            break;
        printf ("Client: %s\n", reply);
        free (reply);
        sleep (1);
    }
    zctx_destroy (&ctx);
    return NULL;
}
```
so it just keep dumping:
>Client: OK

and never exit.

I was just wondering that will it be better to rewrite `lbbroker2.c/lbbroker3.c` to make them have the same behavior as `lbbroker.c`?

For example, after that `lbbroker2.c` becomes: [lbbroker2.c](https://github.com/myd7349/zguide/blob/master/examples/C/lbbroker2.c)

**Comment by hintjens** [comment]
Sounds like a good idea. Would you make a patch & pull request?

**Comment by myd7349** [comment]
Done!
