### ISSUE TITLE
Guide Python Async Server does not use "zmq_proxy"

### ISSUE THREAD

**Issue by drozzy** [imatix/zguide#576]
The is about python guide http://zguide.zeromq.org/py:all#The-Asynchronous-Client-Server-Pattern.

Section "The Asynchronous Client/Server Pattern". The code does not correctly reflect the c-code.

The polling code in the ServerTask class:

    while True:
        sockets = dict(poll.poll())
        if frontend in sockets:
            ident, msg = frontend.recv_multipart()
            tprint('Server received %s id %s' % (msg, ident))
            backend.send_multipart([ident, msg])
        if backend in sockets:
            ident, msg = backend.recv_multipart()
            tprint('Sending to frontend %s id %s' % (msg, ident))
            frontend.send_multipart([ident, msg])

should be replaced with proxy call:

    zmq.proxy(frontend, backend)

Which can be found in PyZMQ binding's docs here: https://zeromq.github.io/pyzmq/api/zmq.html

That's it!

**Comment by drozzy** [comment]
Pull request here (how do I connect the issue with the pull request?):
https://github.com/imatix/zguide/pull/577

**Comment by hintjens** [comment]
You can add a line

Fixes #123

In the commit message.
