### ISSUE TITLE
Stonehouse and Ironhouse example

### ISSUE THREAD

**Issue by metadings** [imatix/zguide#578]
Is there a way to incorporate the [examples from your blog](http://hintjens.com/blog:49) into the book/the guide on zeromq.org? I'm going to implement them now (even if I don't like the format of a zcert file).

**Comment by metadings** [comment]
I see now this is going into the CZMQ library... I also see zhash, zlist and the like...

May I ask you to implement _something_ in C?

**Comment by hintjens** [comment]
I'm going to be redoing the guide later this year. Including these examples.

**Comment by metadings** [comment]
Nice :) Well I'm asking you about a format I invented which looks in Lazy mode like
	"ZeroHTTP.HTTPResponse" {
		"Status-Code": 200i,
		"Content-Type": "text/plain; charset=UTF-8",
		"Content": 548:"ZeroHTTP.HTTPRequest" {
		"_": "CreateResponse" { },
		"Remote-Address": "127.0.0.1:80",
		"Method": "GET",
		"Path": "/ZeroHTTP.HTTPRequest.CreateResponse",
		"Version": "HTTP/1.1",
		"Host": "eb258cb03c42bf91b46d0074939f7efd67e0b9354e2a497285d7432cf02bcc.78.curve25519.m",
		"User-Agent": "Mozilla/5.0 (Windows NT 6.1; rv:40.0) Gecko/20100101 Firefox/40.0",
		"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Accept-Language": "de-DE,en;q=0.5",
		"Accept-Encoding": "gzip, deflate",
		"Connection": "keep-alive"
	}|,
		"Hello": "World"
	}

**Comment by hintjens** [comment]
Not sure what I'm looking at here. A glitch in the matrix?

**Comment by metadings** [comment]
I need to change here and there **some** bytes, but this is essentially a `byte[]` stream, read from a file or a tcp stream, so you can load and save **anything** into memory...

But the question remains: Are you interested in making this in C?

**Comment by metadings** [comment]
It **should** be easy, but you need something like zhash, zlist and the like.

**Comment by metadings** [comment]
I'm sitting here now banging my head if it was wrong to show you the lazy result of my `ZeroHTTP.HTTPRequest.CreateResponse` method...

What do you say, are you with me (YEAH), are you going to do your own thing (déjà-vu) or do you just ignore this?

**Comment by hintjens** [comment]
Hmm, I'm always open to new stuff.

CZMQ tends to be skeptical of new functionality that doesn't seem useful to
multiple people. The usual pattern is to make a class in some other app or
library and then over time, move it into CZMQ if it seems reusable and
desirable. Otherwise someone is likely to remove it.

Hence our process: define a clear problem. get agreement that it's a real
problem, then solve it minimally.

-Pieter

**Comment by metadings** [comment]
Well I'm not that good in writing and discussing things, as in programming them :)  
(Let's wait and see what happens.)
