### ISSUE TITLE
Want to update Go examples

### ISSUE THREAD

**Issue by magiconair** [imatix/zguide#580]
Hi, 

I've just started looking into ZeroMQ and noticed that the Go examples could use some love. 

The bindings from http://github.com/alecthomas/gozmq are no longer maintained and the author suggests to use the ones from Peter Kleiweg (http://github.com/pebbe/zmq[234]). The API has some slight differences. (e.g. context.Term() instead of context.Close())

Also, the examples are missing the error handling and use debug functions (println).

I'm happy to do the work and send in a pull request if that's OK?

Frank

**Comment by magiconair** [comment]
I guess the thing I need to know is whether the omission of the error handling was deliberate to keep the examples short and to the point.

**Comment by hintjens** [comment]
For sure, pull requests are how we work... you can make the examples as
realistic or simplified as you prefer.

**Comment by magiconair** [comment]
OK, then in the first iteration I'm going to work on updating the dependency and make sure no errors are swallowed.

**Comment by magiconair** [comment]
Duh, just saw that @pebbe has already ported the examples in his repository. I'll ask him whether I can use them to update the docs. Might be a good exercise for myself nevertheless.

**Comment by magiconair** [comment]
Let me close this one since it'll take me some time to finish this. I'll send a pull request when I'm done.
