### ISSUE TITLE
wuserver.cpp does not run on Windows and throws exceptions

### ISSUE THREAD

**Issue by felixvd** [imatix/zguide#581]
I am following the tutorial and come across these errors. Maybe someone can help me out with the last one.

1) "srandom", "random" are used in the code but are not defined. srandom and random have been defined in zhelpers.h in #504 , but it's not referenced. Taking the definitions from that issue works fine.

2) "snprintf" is used but does not work below Visual Studio 2015(!). Defining it to _snprintf works only if _CRT_SECURE_NO_WARNINGS is set, which is annoying. [This copy-pasteable fix](http://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010) worked better and seems more durable.

3) The line `publisher.bind("ipc://weather.ipc")` causes an exception. Commenting it out allows the program to run, but wuclient seems to receive no messages. This stumps me, because ipc isn't mentioned in the client, and I don't see if this line is doing anything in the first place.

Thanks in advance for comments.

**Comment by hintjens** [comment]
IPC doesn't work on Windows... you can use tcp://127.0.0.1 as a workaround.

For the rest... MSVC is strange and you can hack the code to make it work,
I'm not really able to support that in the Guide codebase. Maybe with
#ifdefs in zhelpers.h.

**Comment by felixvd** [comment]
Turns out there was no problem at all after the first two fixes, it just took a while for a message to get through. The code runs fine with changes 1 and 2.

Would you like a pull request with the ipc line commented for Windows and the #ifdef in zhelpers.hpp? There are a few like that already in there.

**Comment by hintjens** [comment]
Sure, pull requests are how we make this... thanks.
