### ISSUE TITLE
The human brain does not have trillions of neurons

### ISSUE THREAD

**Issue by jonnew** [imatix/zguide#596]
In the "fixing the world" section it says
> Code has to run like the human brain, trillions of individual neurons firing off messages to each other,...

The human brain has between 80 and 150 billion neurons. I suppose that because ZMQ is designed for messaging, this sentence could be talking about communications across across human brains, in which case you could expand your claim to 7e9 * 100e9 = 7e20 neurons.

**Comment by hintjens** [comment]
So somewhere between 0.1 trillion and 700 000 000 trillion...? :-) 

I'd say "billions" except it doesn't have the same nice ring to it.

**Comment by jonnew** [comment]
Fair enough!
