### ISSUE TITLE
XPUB/XSUB subscription messages direction seems wrong.

### ISSUE THREAD

**Issue by chao83** [imatix/zguide#597]
In section "The Dynamic Discovery Problem", the last paragraph says:

"The proxy has to forward these subscription messages from subscriber side to publisher side, by reading them from the **XSUB** socket and writing them to the **XPUB** socket." 

I think it should be reading from **XPUB**, and writing to **XSUB** socket.

**Comment by hintjens** [comment]
Thank you for spotting this. I've fixed it in the text (will take a while to get online).

**Comment by shishirpy** [comment]
I think the earlier version,

> "The proxy has to forward these subscription messages from subscriber side to publisher side, by reading them from the XSUB socket and writing them to the XPUB socket."

was the correct version. Either the current text is incorrect or __Figure 14 - Extended Pub-Sub__ is incorrect.

**Comment by guidog** [comment]
Oh... you seem to be right.

As far as I understand that, the filtering is done on the publisher, so the subscriber has to send his subscriptions to the publisher.

**Comment by shishirpy** [comment]
I will open a new issue.
