### ISSUE TITLE
Suggestion: Clarify note about outdated state information in InterBroker example

### ISSUE THREAD

**Issue by msteinhoff** [imatix/zguide#598]
While reading the InterBroking example I stumbled upon the following note for the state flow prototype (peering1.py):

> We don’t set identities on subscribers because if we did then we’d get outdated state information when connecting to running brokers.

I did not immediately understood this so I skipped it but after reading it a second and third time I just could not get this into my head. The manual on setsockopt/ZMQ_IDENTITY was also not helpful until I found this explanation: http://thisthread.blogspot.de/2011/08/high-watermark-for-durable-pubsub.html

> In the ZeroMQ pub/sub pattern, if we set an identity for a subscriber, the publisher keeps the data in queue till it is actually delivered to the subscriber.

So it looks like setting an identity on the state sockets would cause the following to happen:

1. Broker A starts, publishes state messages. State messages are dropped for now because no one is subscribed yet.
2. Broker B starts, connects and gets subscribed with its identity.
3. Broker B now receives state messages.
4. Broker B gets disconnected.
5. Broker A publishes state messages which are queued for the now-established identity of Broker B until HWM is reached and state messages are dropped again.
6. Broker B connects again, now receives all the queued up state messages since the last disconnect which might be outdated in this moment.

To avoid outdated state messages, the identity is not set so that the publisher does not queue messages if a subscriber disconnect from the socket.

We could also go for the overly-complicated solution: set identities, then add timestamps to each message and ignore messages older than 1 second when reconnecting.

Is my understanding correct?

**Comment by hintjens** [comment]
Persistence on pub/sub was removed in 3.0.

Identities are only applicable to dealer sockets in 3.x and later.

You probably should not use identities at all, they are misdesigned and
have several problems.

**Comment by msteinhoff** [comment]
Okay, this explains the problems well: http://hintjens.com/blog:84
