### ISSUE TITLE
What are the ".split" comments in Python guide?

### ISSUE THREAD

**Issue by drozzy** [imatix/zguide#606]
I keep seeing ".split" inside some of the python code listings, e.g. fileio1.py line 40 (https://github.com/drozzy/zguide/blob/master/examples/Python/fileio1.py):

````    
    print ("%i chunks received, %i bytes" % (chunks, total))
    pipe.send(b"OK")

# .split File server thread
# The server thread reads the file from disk in chunks, and sends
# each chunk to the client as a separate message. We only have one
# test file, so open that once and then serve it out as needed:


def server_thread(ctx):
    file = open("testdata", "r")
````

What are those? Should they be removed?

**Comment by hintjens** [comment]
They're used when producing the printed Guide, to break long listings into fragments. They should only be in the C code. So you can remove them from the Python code (I assume they were copied over in some cases.)
