### ISSUE TITLE
Python Examples Are Reversed

### ISSUE THREAD

**Issue by meawoppl** [imatix/zguide#610]
The two of the examples for fileio in python are reversed:
http://zguide.zeromq.org/hx:chapter7#Transferring-Files

examples 2 & 3 are backward wrt. to the description.  
https://github.com/imatix/zguide/blob/master/examples/Python/fileio2.py
https://github.com/imatix/zguide/blob/master/examples/Python/fileio3.py

Should I submit a PR with just the files moved?

**Comment by hintjens** [comment]
Sure, we work with PRs. Thanks.

**Comment by drozzy** [comment]
@meawoppl I've noticed the same thing! See my bug:
https://github.com/imatix/zguide/issues/583

But it's been a while since I read the guide, so I no longer remember what the problem was. 

Can you please make a PR while it is still fresh in your mind? I feel bad for not doing it back then...

**Comment by meawoppl** [comment]
PR above!  Thanks again for zmq.
