### ISSUE TITLE
ZGuide in Python zguide.zeromq.org/py:all also in C#?

### ISSUE THREAD

**Issue by metadings** [imatix/zguide#622]
How do you just generate this awesome link to watch the ZGuide in Python?

	zguide.zeromq.org/py:all

Would you also like to make a link for the ZGuide in C#?

	zguide.zeromq.org/cs:all

**Comment by hintjens** [comment]
In theory it works, http://zguide.zeromq.org/cs:all except in practice
Wikidot cannot save the page. I've asked them to take a look.

**Comment by metadings** [comment]
Awesome!

**Comment by metadings** [comment]
Now I'd just remark, there are some issues using the ZGuide with NoScript and RequestPolicy.

The code samples don't show up, if I don't allow `zeromq.org` in NoScript and `wdfiles.com`, `wikidot.com` (which is ok) but also `github.com`, implicitly `raw.githubusercontent.com` and also `something.cloudfront.net` in RequestPolicy.

**Comment by metadings** [comment]
I also believe you could use a `font-size: 1em` instead of `.82em`!

**Comment by hintjens** [comment]
I don't have control over the request policies.

I've increased the font size, this is rather nicer, thanks.

**Comment by metadings** [comment]
hehe... Thanks to you, ZeroMQ is so awesome. Again.

PS: `RequestPolicy Continued` is an addon for Firefox - I'm using it in blocking mode.
