### ISSUE TITLE
Racket hwclient example: Assertion failed

### ISSUE THREAD

**Issue by jvalleroy** [imatix/zguide#638]
I'm using Racket v6.3 on Debian testing. hwserver is running and I can connect to it with ncat. But hwclient fails with the following:

```
$ racket hwclient.rkt 
Connecting to hello world server…
Sending request 0…
Assertion failed: check () (src/msg.cpp:248)
Aborted
```

**Comment by int3l** [comment]
Please provide the settings of your server and client, and if it is possible - post a snipet of the server/client code that fails, so we can give you an advice or investigate further more.

Thanks for your report.

**Comment by jvalleroy** [comment]
The code is here: https://github.com/imatix/zguide/blob/master/examples/Racket/hwclient.rkt
That's what I'm running, along with hwserver.rkt.

**Comment by int3l** [comment]
It looks like that the [current available bindings for racket](https://docs.racket-lang.org/zeromq/index.html) works only with zeromq up to 3.x.
Additional info: [iracket](https://github.com/spelufo/iracket#readme), [racket-zmq-examples](https://github.com/neomantic/racket-zmq-examples#readme))

You will need to reinstall zeromq with 3.x if you have 4.x.

**Comment by jvalleroy** [comment]
I downgraded to zeromq 3.2.4, and it's working. Thanks!
